/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint for liveness probes.
         *
         *     Returns basic health status and count of running orchestrators.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Orchestrators
         * @description List all registered orchestrator instances.
         *
         *     Returns both running and recently stopped orchestrators from the registry.
         *     Stale entries are cleaned up automatically.
         */
        get: operations["list_orchestrators_api_orchestrators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrators/{instance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Orchestrator
         * @description Get information about a specific orchestrator instance.
         *
         *     Args:
         *         instance_id: The orchestrator instance ID.
         *
         *     Returns:
         *         OrchestratorInfo with instance details.
         *
         *     Raises:
         *         HTTPException 404: If instance not found.
         */
        get: operations["get_orchestrator_api_orchestrators__instance_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrators/{instance_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Orchestrator Status
         * @description Get full status for an orchestrator including tasks and progress.
         *
         *     Args:
         *         instance_id: The orchestrator instance ID.
         *
         *     Returns:
         *         StatusResponse with full execution status.
         *
         *     Raises:
         *         HTTPException 404: If instance not found.
         */
        get: operations["get_orchestrator_status_api_orchestrators__instance_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plans
         * @description List all available plans.
         *
         *     Scans the docs/plans/ directory for markdown plan files.
         */
        get: operations["list_plans_api_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_name}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan Status
         * @description Get status summary for a specific plan.
         *
         *     Args:
         *         plan_name: Name of the plan (without .md extension).
         *
         *     Returns:
         *         StatusSummary with progress information.
         *
         *     Raises:
         *         HTTPException 404: If plan or status not found.
         */
        get: operations["get_plan_status_api_plans__plan_name__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_name}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan Tasks
         * @description Get all tasks for a specific plan.
         *
         *     Args:
         *         plan_name: Name of the plan (without .md extension).
         *
         *     Returns:
         *         List of TaskInfo objects.
         *
         *     Raises:
         *         HTTPException 404: If plan or status not found.
         */
        get: operations["get_plan_tasks_api_plans__plan_name__tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_name}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plan Findings
         * @description List all findings files for a plan.
         *
         *     Args:
         *         plan_name: Name of the plan (without .md extension).
         *
         *     Returns:
         *         List of FindingInfo objects.
         *
         *     Raises:
         *         HTTPException 404: If plan not found.
         */
        get: operations["list_plan_findings_api_plans__plan_name__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_name}/findings/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Finding Content
         * @description Get the content of a specific finding.
         *
         *     Args:
         *         plan_name: Name of the plan (without .md extension).
         *         task_id: The task ID (e.g., "1.1").
         *
         *     Returns:
         *         Dict with task_id and content.
         *
         *     Raises:
         *         HTTPException 404: If finding not found.
         */
        get: operations["get_finding_content_api_plans__plan_name__findings__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrators/{instance_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Orchestrator
         * @description Pause an orchestrator's execution.
         *
         *     The orchestrator will complete the current task before pausing.
         *
         *     Args:
         *         instance_id: The orchestrator instance ID.
         *
         *     Returns:
         *         CommandResponse indicating success or failure.
         */
        post: operations["pause_orchestrator_api_orchestrators__instance_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrators/{instance_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Orchestrator
         * @description Resume a paused orchestrator.
         *
         *     Args:
         *         instance_id: The orchestrator instance ID.
         *
         *     Returns:
         *         CommandResponse indicating success or failure.
         */
        post: operations["resume_orchestrator_api_orchestrators__instance_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrators/{instance_id}/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Shutdown Orchestrator
         * @description Request graceful shutdown of an orchestrator.
         *
         *     Args:
         *         instance_id: The orchestrator instance ID.
         *         force: If True, request immediate shutdown without waiting for current task.
         *
         *     Returns:
         *         CommandResponse indicating success or failure.
         */
        post: operations["shutdown_orchestrator_api_orchestrators__instance_id__shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrators/{instance_id}/skip-task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Skip Task
         * @description Skip a task in the orchestrator's plan.
         *
         *     Uses status-cli.js to mark the task as skipped.
         *
         *     Args:
         *         instance_id: The orchestrator instance ID.
         *         request: SkipTaskRequest with task_id and optional reason.
         *
         *     Returns:
         *         CommandResponse indicating success or failure.
         */
        post: operations["skip_task_api_orchestrators__instance_id__skip_task_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrators/{instance_id}/retry-task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Task
         * @description Reset a failed task for retry.
         *
         *     Changes the task status back to pending so it will be attempted again.
         *
         *     Args:
         *         instance_id: The orchestrator instance ID.
         *         request: RetryTaskRequest with task_id.
         *
         *     Returns:
         *         CommandResponse indicating success or failure.
         */
        post: operations["retry_task_api_orchestrators__instance_id__retry_task_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orchestrators/{instance_id}/events-sse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sse Events
         * @description Server-Sent Events endpoint for real-time event streaming.
         *
         *     Alternative to WebSocket for environments where WebSocket is problematic.
         *     Streams all events for the specified orchestrator instance.
         *
         *     Events are sent in SSE format:
         *     ```
         *     event: status_updated
         *     data: {"type": "status_updated", "timestamp": "...", "instance_id": "...", "data": {...}}
         *
         *     event: heartbeat
         *     data: {"type": "heartbeat", "timestamp": "..."}
         *     ```
         *
         *     Args:
         *         instance_id: The orchestrator instance ID to receive events for.
         *         request: The HTTP request object.
         *
         *     Returns:
         *         StreamingResponse with text/event-stream content type.
         *
         *     Raises:
         *         HTTPException 404: If orchestrator not found.
         */
        get: operations["sse_events_api_orchestrators__instance_id__events_sse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CommandResponse
         * @description Response from a command endpoint.
         */
        CommandResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Error */
            error?: string | null;
        };
        /**
         * FindingInfo
         * @description Information about a task finding.
         */
        FindingInfo: {
            /** Task Id */
            task_id: string;
            /** File Path */
            file_path: string;
            /** Size Bytes */
            size_bytes: number;
            /** Last Modified */
            last_modified: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response.
         */
        HealthResponse: {
            /**
             * Status
             * @default healthy
             * @enum {string}
             */
            status: "healthy" | "degraded" | "unhealthy";
            /**
             * Version
             * @default 1.0.0
             */
            version: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Orchestrators Running
             * @default 0
             */
            orchestrators_running: number;
        };
        /**
         * OrchestratorInfo
         * @description Information about a registered orchestrator instance.
         */
        OrchestratorInfo: {
            /**
             * Id
             * @description Unique orchestrator instance ID
             */
            id: string;
            /**
             * Pid
             * @description Process ID of the orchestrator
             */
            pid: number;
            /**
             * Plan Path
             * @description Path to the plan file being executed
             */
            plan_path: string;
            /**
             * Plan Name
             * @description Name of the plan (derived from filename)
             */
            plan_name: string;
            /**
             * Worktree Path
             * @description Worktree path if using worktrees
             */
            worktree_path?: string | null;
            /**
             * Started At
             * @description ISO timestamp when orchestrator started
             */
            started_at: string;
            /**
             * Last Heartbeat
             * @description ISO timestamp of last heartbeat
             */
            last_heartbeat: string;
            /**
             * Status
             * @description Current orchestrator status
             * @enum {string}
             */
            status: "running" | "stopping" | "stopped" | "crashed";
            /**
             * Socket Path
             * @description Unix socket path for IPC
             */
            socket_path?: string | null;
            /**
             * Is Alive
             * @description Whether the process is still running
             */
            is_alive: boolean;
            /**
             * Is Stale
             * @description Whether the heartbeat is stale
             */
            is_stale: boolean;
        };
        /**
         * PhaseSummary
         * @description Summary of a phase's progress.
         */
        PhaseSummary: {
            /** Phase Number */
            phase_number: number;
            /** Name */
            name: string;
            /** Total Tasks */
            total_tasks: number;
            /** Completed Tasks */
            completed_tasks: number;
            /** Pending Tasks */
            pending_tasks: number;
            /** Failed Tasks */
            failed_tasks: number;
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
        };
        /**
         * PlanInfo
         * @description Information about an available plan.
         */
        PlanInfo: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /**
             * Has Status
             * @default false
             */
            has_status: boolean;
            /** Last Modified */
            last_modified?: string | null;
            /** Output Dir */
            output_dir?: string | null;
        };
        /**
         * RetryTaskRequest
         * @description Request to retry a task.
         */
        RetryTaskRequest: {
            /** Task Id */
            task_id: string;
        };
        /**
         * SkipTaskRequest
         * @description Request to skip a task.
         */
        SkipTaskRequest: {
            /** Task Id */
            task_id: string;
            /** Reason */
            reason?: string | null;
        };
        /**
         * StatusResponse
         * @description Full status response for an orchestrator.
         */
        StatusResponse: {
            /** Instance Id */
            instance_id: string;
            /** Plan Path */
            plan_path: string;
            /** Plan Name */
            plan_name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "paused" | "stopping" | "stopped";
            summary: components["schemas"]["StatusSummary"];
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["TaskInfo"][];
            /**
             * Phases
             * @default []
             */
            phases: components["schemas"]["PhaseSummary"][];
            /** Started At */
            started_at?: string | null;
            /**
             * Iteration
             * @default 0
             */
            iteration: number;
            /**
             * Max Iterations
             * @default 0
             */
            max_iterations: number;
        };
        /**
         * StatusSummary
         * @description Summary of plan execution status.
         */
        StatusSummary: {
            /**
             * Total Tasks
             * @default 0
             */
            total_tasks: number;
            /**
             * Completed
             * @default 0
             */
            completed: number;
            /**
             * Pending
             * @default 0
             */
            pending: number;
            /**
             * In Progress
             * @default 0
             */
            in_progress: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /** Current Phase */
            current_phase?: string | null;
            /**
             * Progress Percent
             * @default 0
             */
            progress_percent: number;
        };
        /**
         * TaskInfo
         * @description Information about a single task.
         */
        TaskInfo: {
            /** Id */
            id: string;
            /** Description */
            description: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "in_progress" | "completed" | "failed" | "skipped";
            /** Phase */
            phase?: string | null;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /** Last Error */
            last_error?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_orchestrators_api_orchestrators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrchestratorInfo"][];
                };
            };
        };
    };
    get_orchestrator_api_orchestrators__instance_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrchestratorInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_orchestrator_status_api_orchestrators__instance_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanInfo"][];
                };
            };
        };
    };
    get_plan_status_api_plans__plan_name__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_tasks_api_plans__plan_name__tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plan_findings_api_plans__plan_name__findings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_finding_content_api_plans__plan_name__findings__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_name: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_orchestrator_api_orchestrators__instance_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_orchestrator_api_orchestrators__instance_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shutdown_orchestrator_api_orchestrators__instance_id__shutdown_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_task_api_orchestrators__instance_id__skip_task_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_task_api_orchestrators__instance_id__retry_task_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sse_events_api_orchestrators__instance_id__events_sse_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
